CREATE TABLE inventory_wheels (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    car_year TEXT NOT NULL,
    wheel_width TEXT NOT NULL,
    wheel_diameter TEXT NOT NULL,
    bolt_pattern TEXT NOT NULL,
    quantity TEXT NOT NULL,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL
);
